### ISSUE TITLE
Create A Wiki!

### ISSUE THREAD

**Issue by J-The-Fox** [J-The-Fox/FRC-Team-5098#2]
As the title implies, create a Wiki documenting code examples and such to hopefully make it easier on how to work things. The big one being WPILib examples but having basic Python and Java examples would be a good idea to add as well

**Comment by J-The-Fox** [comment]
# Update

Added the sections. Just need to populate the pages now

**Comment by J-The-Fox** [comment]
# Update

Added installation pages and added a new quizzes section with the required pages from Dreadfall

**Comment by J-The-Fox** [comment]
# Update

I will close this issue for now as we have most of the wiki planned out. Altough we are still missing some pages. They will be filled in. Most of the big pages have been made (Such as installing the needed software). Pages will be updated as time goes on and time becomes available for me or whoever else to compile the pages.

You can find a wiki discussion here: #3

**Comment by Dreadfall** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Wiki](https://trello.com/c/VqSJ0eeU/1-update-wiki)
